// Generated from packages/sdk-ts/src/browser.ts. Do not edit this file.
// Run: bun packages/sdk-ts/scripts/browser-bundle.ts
// Card compiler output is an intermediate registry-aware plan; explain() is a logical preview.

// src/identifier.ts
function ident(name) {
  if (!isIdentifier(name))
    throw new Error(`BAD IDENTIFIER: "${name}"`);
  return `"${name}"`;
}
function isIdentifier(name) {
  return name.length <= 63 && isLogicalIdentifier(name);
}
function isLogicalIdentifier(name) {
  return /^[a-z_][a-z0-9_]*$/.test(name);
}

// src/ref.ts
function parseRef(ref) {
  const parts = ref.split("/");
  if (parts.length !== 3) {
    throw new Error(`BAD REF: "${ref}" — expected book/deck/id (3 segments, got ${parts.length})`);
  }
  const [book, deck, id] = parts;
  if (!book || !deck || !id) {
    throw new Error(`BAD REF: "${ref}" — book, deck, and id are all required`);
  }
  validateIdentifier(book, "book");
  validateIdentifier(deck, "deck");
  if (!isValidUuid(id)) {
    throw new Error(`BAD REF: "${ref}" — id is not a full UUID`);
  }
  return { book, deck, id };
}
function formatRef(ref) {
  const validated = parseRef(`${ref.book}/${ref.deck}/${ref.id}`);
  return `${validated.book}/${validated.deck}/${validated.id}`;
}
function makeRef(book, deck, id) {
  return parseRef(`${book}/${deck}/${id}`);
}
function isValidUuid(s) {
  const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  return uuidRe.test(s);
}
function parseDeckPattern(pattern) {
  const parts = pattern.split("/");
  if (parts.length !== 2) {
    throw new Error(`BAD DECK PATTERN: "${pattern}" — expected book/deck (2 segments)`);
  }
  const [book, deck] = parts;
  if (book !== "*")
    validateIdentifier(book, "book pattern");
  if (deck !== "*")
    validateIdentifier(deck, "deck pattern");
  return { book, deck };
}
function validateIdentifier(value, label) {
  if (!isLogicalIdentifier(value)) {
    throw new Error(`BAD REF: ${label} "${value}" is not lower_snake`);
  }
}

// src/nonblank.ts
function isNonblankText(value) {
  return typeof value === "string" && !value.includes("\x00") && /[^\u0009-\u000D\u0020]/u.test(value);
}

// src/uuidv7.ts
function uuidv7(timestampMs) {
  const ts = timestampMs ?? Date.now();
  if (!Number.isSafeInteger(ts) || ts < 0 || ts > 281474976710655) {
    throw new RangeError("UUIDV7 TIMESTAMP: expected an integer from 0 through 2^48 - 1 milliseconds");
  }
  const bytes = new Uint8Array(16);
  const crypto = globalThis.crypto;
  if (!crypto?.getRandomValues) {
    throw new Error("UUIDV7 RANDOMNESS: Web Crypto getRandomValues is unavailable");
  }
  crypto.getRandomValues(bytes);
  bytes[0] = Math.floor(ts / 1099511627776) & 255;
  bytes[1] = Math.floor(ts / 4294967296) & 255;
  bytes[2] = Math.floor(ts / 16777216) & 255;
  bytes[3] = Math.floor(ts / 65536) & 255;
  bytes[4] = Math.floor(ts / 256) & 255;
  bytes[5] = ts & 255;
  bytes[6] = 112 | bytes[6] & 15;
  bytes[8] = 128 | bytes[8] & 63;
  return formatUuid(bytes);
}
function formatUuid(bytes) {
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0"));
  return hex.slice(0, 4).join("") + "-" + hex.slice(4, 6).join("") + "-" + hex.slice(6, 8).join("") + "-" + hex.slice(8, 10).join("") + "-" + hex.slice(10, 16).join("");
}
function uuidv7Timestamp(id) {
  const bytes = parseUuidBytes(id);
  if (!bytes)
    return null;
  if ((bytes[6] & 240) !== 112)
    return null;
  if ((bytes[8] & 192) !== 128)
    return null;
  const ts = bytes[0] * 1099511627776 + bytes[1] * 4294967296 + bytes[2] * 16777216 + bytes[3] * 65536 + bytes[4] * 256 + bytes[5];
  return Math.floor(ts);
}
function parseUuidBytes(id) {
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {
    return null;
  }
  const clean = id.replace(/-/g, "");
  const bytes = new Uint8Array(16);
  for (let i = 0;i < 16; i++) {
    const byte = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(byte))
      return null;
    bytes[i] = byte;
  }
  return bytes;
}

// src/query-builders.ts
var LOGICAL_DECK_SQL = '"__yutabase_logical_book__"."__yutabase_logical_deck__"';
var CLAIM_KINDS = Object.freeze([
  "witnessed",
  "live",
  "cached",
  "computed",
  "declared"
]);
function parseClaimKind(value, operation) {
  if (CLAIM_KINDS.includes(value))
    return value;
  throw new Error(`${operation}: unknown claim kind "${value}"`);
}
function requireClaimSources(operation, how, src) {
  if (src !== undefined && (!Array.isArray(src) || Array.from(src).some((locator) => !isNonblankText(locator)))) {
    throw new Error(`${operation}: src entries must be non-blank strings without NUL`);
  }
  if ((how === "cached" || how === "computed") && (!src || src.length === 0)) {
    throw new Error(`${operation}: how=${how} requires src — honesty header`);
  }
}
function compileCardQuery(ref) {
  return {
    sql: `SELECT * FROM ${LOGICAL_DECK_SQL} WHERE ${ident("id")} = $1`,
    params: [ref.id],
    deckTarget: { kind: "card", book: ref.book, deck: ref.deck }
  };
}
function compileTraversalQuery(ref, direction, word, secondHop) {
  assertTraversalDirection(direction, "TRAVERSE direction");
  if (secondHop) {
    assertTraversalDirection(secondHop.direction, "TRAVERSE second-hop direction");
  }
  const firstOut = direction === "->";
  const params = [ref.book, ref.deck, ref.id];
  const firstStart = firstOut ? "from" : "to";
  const firstEnd = firstOut ? "to" : "from";
  if (!secondHop) {
    params.push(word);
    return {
      sql: `
        SELECT t.${firstEnd}_book AS book, t.${firstEnd}_deck AS deck, t.${firstEnd}_id AS id,
               t.note, t.at, t.by, t.how, t.src, t.id AS thread_id,
               t.word, t.word_version, v.gloss, v.inverse,
               ${direction === "->" ? "v.gloss" : "v.inverse"} AS reading,
               jsonb_build_array(${edgeJsonSql("t", "v", direction)}) AS path
        FROM yu.threads t
        JOIN yu.word_versions v
          ON v.word = t.word AND v.word_version = t.word_version
        WHERE t.word = $4
          AND t.${firstStart}_book = $1 AND t.${firstStart}_deck = $2 AND t.${firstStart}_id = $3
        ORDER BY t.at DESC, t.id DESC
      `.trim(),
      params
    };
  }
  const secondOut = secondHop.direction === "->";
  const secondStart = secondOut ? "from" : "to";
  const secondEnd = secondOut ? "to" : "from";
  params.push(word, secondHop.word);
  return {
    sql: `
      SELECT t2.${secondEnd}_book AS book, t2.${secondEnd}_deck AS deck, t2.${secondEnd}_id AS id,
             t2.note, t2.at, t2.by, t2.how, t2.src, t2.id AS thread_id,
             t2.word, t2.word_version, v2.gloss, v2.inverse,
             ${secondHop.direction === "->" ? "v2.gloss" : "v2.inverse"} AS reading,
             jsonb_build_array(
               ${edgeJsonSql("t1", "v1", direction)},
               ${edgeJsonSql("t2", "v2", secondHop.direction)}
             ) AS path
      FROM yu.threads t1
      JOIN yu.threads t2
        ON t2.${secondStart}_book = t1.${firstEnd}_book
       AND t2.${secondStart}_deck = t1.${firstEnd}_deck
       AND t2.${secondStart}_id = t1.${firstEnd}_id
      JOIN yu.word_versions v1
        ON v1.word = t1.word AND v1.word_version = t1.word_version
      JOIN yu.word_versions v2
        ON v2.word = t2.word AND v2.word_version = t2.word_version
      WHERE t1.word = $4
        AND t1.${firstStart}_book = $1 AND t1.${firstStart}_deck = $2 AND t1.${firstStart}_id = $3
        AND t2.word = $5
      ORDER BY t2.at DESC, t2.id DESC
    `.trim(),
    params
  };
}
function assertTraversalDirection(value, field) {
  if (value !== "->" && value !== "<-") {
    throw new Error(`${field}: expected "->" or "<-"`);
  }
}
function edgeJsonSql(threadAlias, versionAlias, direction) {
  return `jsonb_build_object(
    'thread_id', ${threadAlias}.id,
    'word', ${threadAlias}.word,
    'word_version', ${threadAlias}.word_version,
    'gloss', ${versionAlias}.gloss,
    'inverse', ${versionAlias}.inverse,
    'direction', '${direction}',
    'reading', ${direction === "->" ? `${versionAlias}.gloss` : `${versionAlias}.inverse`},
    'from_ref', ${threadAlias}.from_book || '/' || ${threadAlias}.from_deck || '/' || ${threadAlias}.from_id::text,
    'to_ref', ${threadAlias}.to_book || '/' || ${threadAlias}.to_deck || '/' || ${threadAlias}.to_id::text,
    'note', ${threadAlias}.note,
    'at', ${threadAlias}.at,
    'by', ${threadAlias}.by,
    'how', ${threadAlias}.how,
    'src', ${threadAlias}.src
  )`;
}
function compileThreadQuery(input) {
  const how = parseClaimKind(input.how, "THREAD");
  requireClaimSources("THREAD", how, input.src);
  const params = [
    uuidv7(),
    input.word,
    input.from.book,
    input.from.deck,
    input.from.id,
    input.to.book,
    input.to.deck,
    input.to.id
  ];
  let nextParam = 9;
  let noteParam = "NULL";
  if (input.note !== undefined) {
    noteParam = `$${nextParam++}`;
    params.push(input.note);
  }
  const howParam = `$${nextParam++}`;
  params.push(how);
  const claimantParamIndex = params.length;
  const byParam = `$${nextParam++}`;
  params.push("__CLAIMANT__");
  const atParam = `$${nextParam++}`;
  params.push(new Date().toISOString());
  let srcParam = "NULL";
  if (input.src !== undefined) {
    srcParam = `$${nextParam}`;
    params.push([...input.src]);
  }
  return {
    sql: `
      INSERT INTO yu.threads (id, word, from_book, from_deck, from_id, to_book, to_deck, to_id, note, at, by, how, src)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, ${noteParam}, ${atParam}, ${byParam}, ${howParam}, ${srcParam})
      RETURNING *
    `.trim(),
    params,
    claimantParamIndex
  };
}
function compileSeverQuery(input) {
  const how = parseClaimKind(input.how, "SEVER");
  requireClaimSources("SEVER", how, input.src);
  return {
    sql: "SELECT yu.sever($1, $2, $3, $4)",
    params: [input.threadId, "__CLAIMANT__", how, input.src ? [...input.src] : null],
    claimantParamIndex: 1
  };
}

// src/youspeak.ts
var DEFAULT_CARDS_LIMIT = 100;
var MAX_CARDS_LIMIT = 1000;
var CORE_YOUSPEAK_FORMS = Object.freeze([
  "hello",
  "card",
  "cards",
  "traverse",
  "thread",
  "sever",
  "explain"
]);
function compile(input) {
  const trimmed = input.trim();
  if (trimmed === "")
    throw new Error("EMPTY QUERY");
  if (trimmed === "hello") {
    return { sql: "SELECT 1", params: [] };
  }
  const explainMatch = trimmed.match(/^explain\s+"(.+)"$/);
  if (explainMatch) {
    const inner = compile(explainMatch[1]);
    return {
      sql: "SELECT $1::text AS sql",
      params: [renderLogicalQuery(inner)]
    };
  }
  const cardMatch = trimmed.match(/^card\s+(\S+)$/);
  if (cardMatch) {
    return compileCardQuery(parseRef(cardMatch[1]));
  }
  const cardsMatch = trimmed.match(/^cards\s+(\S+)(?:\s+where\s+(.+?))?(?:\s+newest\s+(\S+))?$/);
  if (cardsMatch) {
    const [_, deckRef, wherePart, limitStr] = cardsMatch;
    const dp = parseDeckRef(deckRef);
    const limit = parseCardsLimit(limitStr);
    const where = wherePart ? parseWhere(wherePart) : undefined;
    return compileCards(dp.book, dp.deck, where, limit);
  }
  const threadMatch = trimmed.match(/^thread\s+(\S+)\s+--(\S+?)-->\s+(\S+)(?:\s+note\s+"([^"]*)")?(?:\s+how\s+(\S+))?(?:\s+src\s+(.+))?$/);
  if (threadMatch) {
    const [_, fromRef, word, toRef, note, how, srcPart] = threadMatch;
    const from = parseRef(fromRef);
    const to = parseRef(toRef);
    if (!how)
      throw new Error("THREAD REQUIRES how — no default (honesty header)");
    const src = srcPart ? srcPart.split(/\s+/) : undefined;
    return compileThreadQuery({
      from,
      word,
      to,
      note,
      how: parseClaimKind(how, "THREAD"),
      src
    });
  }
  const severMatch = trimmed.match(/^sever\s+(\S+)\s+how\s+(\S+)(?:\s+src\s+(.+))?$/);
  if (severMatch) {
    const [_, threadId, how, srcPart] = severMatch;
    const src = srcPart ? srcPart.split(/\s+/) : undefined;
    return compileSeverQuery({
      threadId,
      how: parseClaimKind(how, "SEVER"),
      src
    });
  }
  const traverseResult = tryTraversal(trimmed);
  if (traverseResult)
    return traverseResult;
  throw new Error(`UNRECOGNIZED QUERY: "${trimmed}" — outside frozen YOUSPEAK core v0.1 ` + "(hello, card, cards, traversal, thread, sever)");
}
function tryTraversal(input) {
  const twoHopMatch = input.match(/^(\S+)\s+(->|<-)\s+(\S+)\s+(->|<-)\s+(\S+)$/);
  if (twoHopMatch) {
    const [_, refStr, dir1, word1, dir2, word2] = twoHopMatch;
    const ref = parseRef(refStr);
    return compileTraversalQuery(ref, dir1, word1, { direction: dir2, word: word2 });
  }
  const oneHopMatch = input.match(/^(\S+)\s+(->|<-)\s+(\S+)$/);
  if (oneHopMatch) {
    const [_, refStr, dir, word] = oneHopMatch;
    const ref = parseRef(refStr);
    return compileTraversalQuery(ref, dir, word);
  }
  return null;
}
function compileCards(book, deck, where, limit) {
  let sql = `SELECT * FROM ${LOGICAL_DECK_SQL}`;
  const params = [];
  let paramIdx = 1;
  if (where && where.conditions.length > 0) {
    const adjusted = where.conditions.map((c) => c.replace(/\$(\d+)/g, (_, n) => `$${paramIdx + parseInt(n, 10) - 1}`));
    where.params.forEach((p) => params.push(p));
    paramIdx += where.params.length;
    sql += ` WHERE ` + adjusted.join(" AND ");
  }
  sql += ` ORDER BY ${ident("at")} DESC NULLS LAST, ${ident("id")} DESC`;
  sql += ` LIMIT $${paramIdx}`;
  params.push(limit);
  return { sql: sql.trim(), params, deckTarget: { kind: "cards", book, deck } };
}
function parseWhere(input) {
  const conditions = [];
  const params = [];
  const parts = splitWhereConditions(input);
  for (const part of parts) {
    const m = part.match(/^(\.?[\w]+)\s*(=|!=|>=|<=|>|<)\s*(?:"([^"]*)"|(\S+))$/);
    if (!m) {
      throw new Error(`BAD WHERE: "${part}" — expected column op value (e.g. status="pending" or .how="witnessed")`);
    }
    const [_, col, op, quotedVal, bareVal] = m;
    const value = quotedVal ?? bareVal;
    const columnName = col.startsWith(".") ? col.slice(1) : col;
    if (!isIdentifier(columnName)) {
      throw new Error(`BAD COLUMN: "${columnName}" — not a valid column name`);
    }
    conditions.push(`${ident(columnName)} ${op} $${params.length + 1}`);
    params.push(value);
  }
  return { conditions, params };
}
function splitWhereConditions(input) {
  const parts = [];
  let start = 0;
  let quoted = false;
  for (let index = 0;index < input.length; index++) {
    if (input[index] === '"') {
      quoted = !quoted;
      continue;
    }
    if (quoted || !/\s/.test(input[index]))
      continue;
    const separator = input.slice(index).match(/^\s+and\s+/i);
    if (!separator)
      continue;
    parts.push(input.slice(start, index).trim());
    index += separator[0].length - 1;
    start = index + 1;
  }
  parts.push(input.slice(start).trim());
  return parts;
}
function parseDeckRef(s) {
  const parts = s.split("/");
  if (parts.length !== 2)
    throw new Error(`BAD DECK REF: "${s}" — expected book/deck`);
  if (!isLogicalIdentifier(parts[0]) || !isLogicalIdentifier(parts[1])) {
    throw new Error(`BAD DECK REF: "${s}" — book and deck must be lower_snake`);
  }
  return { book: parts[0], deck: parts[1] };
}
function parseCardsLimit(raw) {
  if (raw === undefined)
    return DEFAULT_CARDS_LIMIT;
  if (!/^[1-9][0-9]*$/.test(raw)) {
    throw new Error(`BAD LIMIT: newest must be an integer from 1 to ${MAX_CARDS_LIMIT}`);
  }
  const parsed = BigInt(raw);
  if (parsed > BigInt(MAX_CARDS_LIMIT)) {
    throw new Error(`BAD LIMIT: newest must be an integer from 1 to ${MAX_CARDS_LIMIT}`);
  }
  return Number(parsed);
}
function explain(query) {
  return renderLogicalQuery(compile(query));
}
function renderLogicalQuery(compiled) {
  const withValues = compiled.sql.replace(/\$(\d+)/g, (placeholder, rawIndex) => {
    const index = Number.parseInt(rawIndex, 10) - 1;
    if (index < 0 || index >= compiled.params.length)
      return placeholder;
    return sqlLiteral(compiled.params[index]);
  });
  if (!compiled.deckTarget)
    return withValues;
  return withValues.replace(LOGICAL_DECK_SQL, `${quoteLogicalLabel(compiled.deckTarget.book)}.${quoteLogicalLabel(compiled.deckTarget.deck)}`);
}
function quoteLogicalLabel(value) {
  return `"${value.replace(/"/g, '""')}"`;
}
function sqlLiteral(value) {
  if (value === null)
    return "NULL";
  if (typeof value === "string")
    return `'${value.replace(/'/g, "''")}'`;
  if (typeof value === "number") {
    if (!Number.isFinite(value))
      throw new Error("EXPLAIN: non-finite numeric parameter");
    return String(value);
  }
  if (typeof value === "bigint")
    return value.toString();
  if (typeof value === "boolean")
    return value ? "TRUE" : "FALSE";
  if (value instanceof Date)
    return `'${value.toISOString()}'`;
  if (Array.isArray(value))
    return `ARRAY[${value.map(sqlLiteral).join(", ")}]`;
  throw new Error(`EXPLAIN: unsupported parameter type ${typeof value}`);
}
export {
  uuidv7Timestamp,
  uuidv7,
  parseRef,
  parseDeckPattern,
  makeRef,
  ident,
  formatRef,
  explain,
  compile,
  CORE_YOUSPEAK_FORMS,
  CLAIM_KINDS
};
