import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const packageRoot = resolve(import.meta.dir, "..");
const outputPath = resolve(packageRoot, "..", "..", "apps", "youspeak.mjs");
const generatedHeader =
  "// Generated from packages/sdk-ts/src/browser.ts. Do not edit this file.\n" +
  "// Run: bun packages/sdk-ts/scripts/browser-bundle.ts\n" +
  "// Card compiler output is an intermediate registry-aware plan; explain() is a logical preview.\n\n";

const result = await Bun.build({
  entrypoints: [join(packageRoot, "src", "browser.ts")],
  target: "browser",
  format: "esm",
  minify: false,
  sourcemap: "none",
  write: false,
});
if (!result.success || result.outputs.length !== 1) {
  for (const log of result.logs) console.error(log);
  throw new Error("browser bundle: canonical compiler build failed");
}

const expected = generatedHeader + await result.outputs[0].text();
if (process.argv.includes("--check")) {
  const actual = readFileSync(outputPath, "utf8");
  if (actual !== expected) {
    throw new Error(
      "browser bundle: apps/youspeak.mjs is stale; run bun packages/sdk-ts/scripts/browser-bundle.ts",
    );
  }
  console.log("browser bundle: canonical artifact is current");
} else {
  await Bun.write(outputPath, expected);
  console.log(`browser bundle: wrote ${outputPath}`);
}
